# -*- coding: utf-8 -*-
"""chatGPT_Text_to_MIDI (advanced moode).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q0M1xdRtXTme6OOSlrhUxbj_NhfxYTO-

# ChatGPT Text-to-MIDI
![Alt Text](https://drive.google.com/uc?id=1Jm6IoeHK_JDTF0hKjxoZQqy6vIXF1m7k)

## Hey there!
### Buckle up, because in this dazzling notebook we're about to morph text generated by ChatGPT into a jazzy MIDI files. Isn't that just the bee's knees? For days on end, what a fabulous time to make music!

# Not in The Nobodies Collective?
## Hop on the bandwagon:
https://www.patreon.com/NobodyandTheComputer

<hr style="border: 1px solid black;">

# FIRST START WITH THE MELODY

![Alt Text](https://drive.google.com/uc?id=1of7X_n50RRxy6Ik5fFxqwETkfZbk-KDs)

# HOW TO:
1. Copy this document:
https://www.patreon.com/posts/chatgpt-prompt-84107618
2. Paste in chatGPT (use V4 for better results)
3. Copy the chatGPT text generation.<br>
be shure that you have this format:<br>
[(note, duration),(note,duration),...]<br>
has to be like that, starting with the "[", inside pairs of (value, value) and finishing with "]".<br>
Any other format will end up in an error.<br>
And ve sgure that the name of the variable is "melody_pitch_duration_data"
4. Run the cells


![Alt Text](https://drive.google.com/uc?id=1Uskezln-W0NgEXt8wHzaicc8sLeok2AX)
"""

# @markdown ### Run this cell to set all your notebook to make MIDI ;-)

# !pip install mido
# !pip install MIDIUtil

# Paste the chatGPT text here:

melody_pitch_duration_data = [
    (60, 0.125),
    (63, 0.083),
    (65, 0.083),
    (67, 0.167),
    (70, 0.167),
    (72, 0.125),
    (75, 0.083),
    (77, 0.083),
    (79, 0.167),
    (82, 0.167),
    (84, 0.125),
    (87, 0.083),
    (89, 0.083),
    (91, 0.167),
    (94, 0.167),
    (96, 0.125),
    (99, 0.083),
    (101, 0.083),
    (103, 0.167),
    (106, 0.167),
]

# @markdown ### Run this cell and th MIDI with the melody will be in your download folder
from mido import Message, MidiFile, MidiTrack

# Constants
TICKS_PER_BEAT = 480  # Standard for most DAWs
BEATS_PER_MINUTE = 120  # Tempo
SECONDS_PER_MINUTE = 60
TICKS_PER_SECOND = TICKS_PER_BEAT * BEATS_PER_MINUTE / SECONDS_PER_MINUTE

# Create a new MIDI file
mid = MidiFile(ticks_per_beat=TICKS_PER_BEAT)

# Create a new track
track = MidiTrack()

# Append the track to the MIDI file
mid.tracks.append(track)

# Convert your data into MIDI events
for note, duration in melody_pitch_duration_data:
    # If there's a silence, don't make a note event
    if note != 0:
        # Add a note on event
        track.append(Message("note_on", note=note, velocity=64, time=0))

    # Wait for the duration of the note/silence
    # We multiply by TICKS_PER_SECOND because duration is in seconds
    track.append(Message("note_off", note=note, velocity=64, time=int(duration * TICKS_PER_SECOND)))

# Save the MIDI file
mid.save("melody.mid")

# Download the file
from google.colab import files

files.download("melody.mid")

"""<hr style="border: 1px solid black;">

# LETS GENERATE SOME A.I. CHORDS

![Alt Text](https://drive.google.com/uc?id=1ibHjgztLuZDUxHOA-LQ2UmMyYLCxC6RA)

# HOW TO:
1. Copy this document:
https://www.patreon.com/posts/chatgpt-prompt-84107694
2. Paste in chatGPT (use V4 for better results)
3. Copy the chatGPT text generation.<br>
be shure that you have this format:<br>
[((note, note) duration)),((note,note, note),duration)),...]<br>
has to be like that, starting with the "[", inside pairs of (value, value) and finishing with "]".<br>
Any other format will end up in an error.<br>
use "chord_pitch_duration_data" as the name variable. Not other
4. Run the next cells


![Alt Text](https://drive.google.com/uc?id=1FB-SmF1GLwrYEVuEvMp7ukBND663fEEk)
"""

# Paste the chatGPT text here:

chords_pitch_duration_data = [
    ((60, 63, 67), 0.5),
    ((62, 65, 69), 0.5),
    ((64, 67, 71), 0.5),
    ((66, 69, 73), 0.5),
    ((68, 71, 75), 0.5),
    ((70, 73, 77), 0.5),
    ((72, 75, 79), 0.5),
    ((74, 77, 81), 0.5),
    ((76, 79, 83), 0.5),
    ((78, 81, 85), 0.5),
    ((80, 83, 87), 0.5),
    ((82, 85, 89), 0.5),
]

x = [
    [("D4", "F4", "A4"), 0.25],
    [("C4", "E4", "G4"), 0.25],
    [(None), 0.5],
    [("D4"), 0.25],
    [("C4"), 0.25],
    [("B3"), 0.25],
    [("A3"), 0.5],
    [("G3"), 0.25],
    [(None), 0.5],
    [("A3", "C4", "E4"), 0.25],
    [("G3", "B3", "D4"), 0.25],
    [("F3", "A3", "C4"), 1],
    [("D3", "F3", "A3"), 0.25],
    [("E3", "G3", "B3"), 0.25],
    [("D3", "F3", "A3"), 1.5],
    [("G3", "B3", "D4"), 1],
    [(None), 1],
    [("D4"), 0.125],
    [("E4"), 0.125],
    [("F4"), 0.125],
    [("G4"), 0.125],
    [("A4"), 1],
    [("G4"), 1],
    [(None), 1],
]

# @markdown ### Run this cell and th MIDI with the chordswill be in your download folder
from midiutil.MidiFile import MIDIFile

midi_file = MIDIFile(1)

tempo = 120
midi_file.addTempo(0, 0, tempo)

instrument = 0  # Acoustic Grand Piano
midi_file.addProgramChange(0, 0, 0, instrument)

channel = 0
volume = 80

# Add chord notes
current_time = 0
for chord_pitches, duration in chords_pitch_duration_data:
    for pitch in chord_pitches:
        midi_file.addNote(track=0, channel=channel, pitch=pitch, time=current_time, duration=duration, volume=volume)
    current_time += duration

with open("chords.mid", "wb") as output_file:
    midi_file.writeFile(output_file)

# Download the MIDI file (if using Google Colab)
from google.colab import files

files.download("chords.mid")

"""<hr style="border: 1px solid black;">

# What about Drums?

![Alt Text](https://drive.google.com/uc?id=1tZa4fqtK11EHNuepbboMgKuLyc1zrunh)

# HOW TO:
1. Copy this document:
https://www.patreon.com/posts/chatgpt-prompt-84107718
2. Paste in chatGPT (use V4 for better results)
3. Copy the chatGPT text generation.<br>
be shure that you have this format:<br>
drum_pitch_duration_data = [<br>
((note, note), duration, velocity), <br>
(note,duration, velocity), (note,note, note), duration,
velocity)<br>,...,<br>
etc,<br>
]<br>
has to be like that, starting with the "[", inside pairs of (value, value) and finishing with "]".<br>
Any other format will end up in an error.<br>
use "drum_pitch_duration_data" as the name variable. Not other
4. Run the next cells
"""

# paste chatGPT text here:

drum_pitch_duration_data = [
    ((36,), 0.125, 127),  # Bass Drum 1
    ((38, 44), 0.25, 110),  # Snare Drum 1 + Pedal Hi-hat
    ((38,), 0.125, 115),  # Snare Drum 1
    ((36,), 0.1875, 127),  # Bass Drum 1
    ((40,), 0.125, 120),  # Snare Drum 2
    ((38, 44), 0.25, 127),  # Snare Drum 1 + Pedal Hi-hat
    ((51,), 0.375, 115),  # Ride Cymbal 1
    ((40, 44), 0.125, 120),  # Snare Drum 2 + Pedal Hi-hat
    ((38,), 0.25, 115),  # Snare Drum 1
    ((36,), 0.375, 127),  # Bass Drum 1
    ((48, 49), 0.125, 120),  # High Tom 2 + Crash Cymbal 1
    ((36, 42), 0.1875, 127),  # Bass Drum 1 + Closed Hi-hat
    ((51,), 0.375, 115),  # Ride Cymbal 1
    ((38, 44), 0.125, 120),  # Snare Drum 1 + Pedal Hi-hat
    ((51,), 0.125, 115),  # Ride Cymbal 1
    ((40,), 0.125, 120),  # Snare Drum 2
    ((38, 44), 0.375, 127),  # Snare Drum 1 + Pedal Hi-hat
    ((36, 49), 0.25, 127),  # Bass Drum 1 + Crash Cymbal 1
    ((40, 44), 0.125, 120),  # Snare Drum 2 + Pedal Hi-hat
    ((36,), 0.25, 115),  # Bass Drum 1
    ((38,), 0.375, 127),  # Snare Drum 1
    ((51, 49), 0.125, 120),  # Ride Cymbal 1 + Crash Cymbal 1
    ((38, 44), 0.1875, 127),  # Snare Drum 1 + Pedal Hi-hat
    ((51,), 0.375, 115),  # Ride Cymbal 1
    ((36, 44), 0.125, 120),  # Bass Drum 1 + Pedal Hi-hat
    ((51,), 0.125, 115),  # Ride Cymbal 1
    ((38,), 0.125, 120),  # Snare Drum 1
    ((51, 44), 0.375, 127),  # Ride Cymbal 1 + Pedal Hi-hat
    ((38, 49), 0.25, 127),  # Snare Drum 1 + Crash Cymbal 1
]

# @markdown ### Run this cell and th MIDI with the Drums will be in your download folder
from mido import Message, MidiFile, MidiTrack

# Create a new MIDI file
mid = MidiFile()
track = MidiTrack()
mid.tracks.append(track)

ticks_per_beat = mid.ticks_per_beat  # Default is 480
ticks_per_note = int(ticks_per_beat * 0.25)  # Assuming tempo is 120 bpm, this is the number of ticks for a quarter note

for note in drum_pitch_duration_data:
    if isinstance(note[0], tuple):  # If more than one note at the same time
        for n in note[0]:
            track.append(Message("note_on", note=n, velocity=note[2], time=0))
        track.append(Message("note_off", note=n, velocity=note[2], time=int(note[1] * ticks_per_note)))
    else:
        track.append(Message("note_on", note=note[0], velocity=note[2], time=0))
        track.append(Message("note_off", note=note[0], velocity=note[2], time=int(note[1] * ticks_per_note)))

# Save the MIDI file
mid.save("artb.mid")
from google.colab import files

files.download("artb.mid")

"""# Here are some tips for navigating your DAW:
![Alt Text](https://drive.google.com/uc?id=107KkAWtoDpTHhwsdEH9QMv6BU4OIVow1)

## 1. Sometimes the MIDI file generated by ChatGPT has a very fast tempo and not the 120 bpm to which the MIDI is programmed. For this, all DAWs have a way to lower or raise the bpm of the MIDI.
<br>

## 2. It's normal that you might need to adjust some MIDI notes to keep them in time. The outputs from ChatGPT are raw and require some fine-tuning.
"""
